version: 2

multi-ecosystem-groups:
  all-updates:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "all-updates"
    patterns: ["*"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "all-updates"
    patterns: ["*"]
    schedule:
      interval: "weekly"
